apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare
type: Opaque
stringData:
  # Elasticsearch (leave empty if ES security is disabled)
  ELASTICSEARCH_PASSWORD: ""

  # MongoDB connection - using MongoDB Atlas
  MONGODB_URI: "mongodb+srv://Cluster55211:jFv69FbRu9Drq9Vq@cluster55211.ud0vx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster55211"
  MONGODB_DATABASE: "healthcare_aiops"

  # JWT Secret for authentication
  JWT_SECRET: "healthcare-aiops-jwt-secret-change-in-prod"
